name: 'Continuous Delivery'

env:
  SERVICE_NAME: mle-challenge-latam-service
  PROJECT_ID: project-bastian
  REGION: us-east1
  REGISTRY: us-east1-docker.pkg.dev
  REPOSITORY: mle-challenge-latam

on:
  workflow_run:
    workflows: ['Continuous Integration']
    types: [completed]
    branches: [main, develop]

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Google Cloud Auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}
  
      - name: Deploy to Cloud Run
        env:
          IMAGE_URL: ${{ env.REGISTRY }}/${{ env.PROJECT_ID }}/${{ env.REPOSITORY }}/${{ env.SERVICE_NAME }}
        run: |
          gcloud run deploy ${{ env.SERVICE_NAME }} \
            --image $IMAGE_URL:latest \
            --region ${{ env.REGION }} \
            --allow-unauthenticated \
            --platform managed \
            --project ${{ env.PROJECT_ID }} \
            --memory 2Gi \
            --cpu 1